techpack: camera/audio: Fix error cause a function declaration is deprecated
clang 17.0.0: error

./techpack/audio/asoc/bengal.c:1090:8: error: type specifier missing,defaults to 'int' [-Werror,-Wimplicit-int]

../techpack/camera/drivers/wl2866d/wl2866d.c:143:30: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]

and more...

Signed-off-by: Asyanx